package com.h3c.imc.acm.acmuserservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-08-03T14:09:57.067+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://acm.imc.h3c.com/acmUserService", name = "acmUserServicePortType")
@XmlSeeAlso({com.h3c.imc.common.ws.xsd.ObjectFactory.class, com.h3c.imc.acmws.user.security.xsd.ObjectFactory.class, com.h3c.imc.acmws.user.accessuser.xsd.ObjectFactory.class, com.h3c.imc.acmws.user.service.xsd.ObjectFactory.class, ObjectFactory.class, com.h3c.imc.acmws.user.ldap.xsd.ObjectFactory.class, com.h3c.imc.acmws.user.blacklist.xsd.ObjectFactory.class, com.h3c.imc.acmws.user.onlineuser.xsd.ObjectFactory.class, com.h3c.imc.acmws.user.parameter.xsd.ObjectFactory.class})
public interface AcmUserServicePortType {

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:modifyAcmUserCreateTime", output = "urn:modifyAcmUserCreateTimeResponse")
    @RequestWrapper(localName = "modifyAcmUserCreateTime", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.ModifyAcmUserCreateTime")
    @WebMethod(action = "urn:modifyAcmUserCreateTime")
    @ResponseWrapper(localName = "modifyAcmUserCreateTimeResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.ModifyAcmUserCreateTimeResponse")
    public com.h3c.imc.common.ws.xsd.WSCommonResult modifyAcmUserCreateTime(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        java.lang.String param0,
        @WebParam(name = "param1", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        javax.xml.datatype.XMLGregorianCalendar param1
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:queryAcmUser", output = "urn:queryAcmUserResponse")
    @RequestWrapper(localName = "queryAcmUser", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.QueryAcmUser")
    @WebMethod(action = "urn:queryAcmUser")
    @ResponseWrapper(localName = "queryAcmUserResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.QueryAcmUserResponse")
    public com.h3c.imc.acmws.user.accessuser.xsd.RetAcmUser queryAcmUser(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        java.lang.String param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:cancelService", output = "urn:cancelServiceResponse")
    @RequestWrapper(localName = "cancelService", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.CancelService")
    @WebMethod(action = "urn:cancelService")
    @ResponseWrapper(localName = "cancelServiceResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.CancelServiceResponse")
    public com.h3c.imc.acmws.user.service.xsd.RetCancelServiceInfo cancelService(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        com.h3c.imc.acmws.user.service.xsd.CancelServiceParam param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:querySyncPolicyInfoList", output = "urn:querySyncPolicyInfoListResponse")
    @RequestWrapper(localName = "querySyncPolicyInfoList", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.QuerySyncPolicyInfoList")
    @WebMethod(action = "urn:querySyncPolicyInfoList")
    @ResponseWrapper(localName = "querySyncPolicyInfoListResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.QuerySyncPolicyInfoListResponse")
    public com.h3c.imc.acmws.user.ldap.xsd.RetAcmSyncPolicyInfoList querySyncPolicyInfoList(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        com.h3c.imc.acmws.user.ldap.xsd.AcmSyncPolicyQueryParam param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:addAcmUser", output = "urn:addAcmUserResponse")
    @RequestWrapper(localName = "addAcmUser", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.AddAcmUser")
    @WebMethod(action = "urn:addAcmUser")
    @ResponseWrapper(localName = "addAcmUserResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.AddAcmUserResponse")
    public com.h3c.imc.common.ws.xsd.WSCommonResult addAcmUser(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        com.h3c.imc.acmws.user.accessuser.xsd.AddAcmUserParam param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:addBindingUser", output = "urn:addBindingUserResponse")
    @RequestWrapper(localName = "addBindingUser", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.AddBindingUser")
    @WebMethod(action = "urn:addBindingUser")
    @ResponseWrapper(localName = "addBindingUserResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.AddBindingUserResponse")
    public com.h3c.imc.common.ws.xsd.WSCommonResult addBindingUser(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        java.lang.Long param0,
        @WebParam(name = "param1", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        java.lang.Long param1
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:kickOut", output = "urn:kickOutResponse")
    @RequestWrapper(localName = "kickOut", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.KickOut")
    @WebMethod(action = "urn:kickOut")
    @ResponseWrapper(localName = "kickOutResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.KickOutResponse")
    public com.h3c.imc.common.ws.xsd.WSCommonResult kickOut(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        java.lang.Long param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:queryParameterByName", output = "urn:queryParameterByNameResponse")
    @RequestWrapper(localName = "queryParameterByName", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.QueryParameterByName")
    @WebMethod(action = "urn:queryParameterByName")
    @ResponseWrapper(localName = "queryParameterByNameResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.QueryParameterByNameResponse")
    public com.h3c.imc.acmws.user.parameter.xsd.RetSystemParameter queryParameterByName(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        java.lang.String param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:clearOnlineInfo", output = "urn:clearOnlineInfoResponse")
    @RequestWrapper(localName = "clearOnlineInfo", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.ClearOnlineInfo")
    @WebMethod(action = "urn:clearOnlineInfo")
    @ResponseWrapper(localName = "clearOnlineInfoResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.ClearOnlineInfoResponse")
    public com.h3c.imc.common.ws.xsd.WSCommonResult clearOnlineInfo(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        java.lang.Long param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:cancelAcmUser", output = "urn:cancelAcmUserResponse")
    @RequestWrapper(localName = "cancelAcmUser", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.CancelAcmUser")
    @WebMethod(action = "urn:cancelAcmUser")
    @ResponseWrapper(localName = "cancelAcmUserResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.CancelAcmUserResponse")
    public com.h3c.imc.common.ws.xsd.WSCommonResult cancelAcmUser(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        java.lang.String param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:queryAcmUserServiceInfo", output = "urn:queryAcmUserServiceInfoResponse")
    @RequestWrapper(localName = "queryAcmUserServiceInfo", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.QueryAcmUserServiceInfo")
    @WebMethod(action = "urn:queryAcmUserServiceInfo")
    @ResponseWrapper(localName = "queryAcmUserServiceInfoResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.QueryAcmUserServiceInfoResponse")
    public com.h3c.imc.acmws.user.accessuser.xsd.RetAcmUserService queryAcmUserServiceInfo(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        java.lang.String param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:modifyInvalidTime", output = "urn:modifyInvalidTimeResponse")
    @RequestWrapper(localName = "modifyInvalidTime", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.ModifyInvalidTime")
    @WebMethod(action = "urn:modifyInvalidTime")
    @ResponseWrapper(localName = "modifyInvalidTimeResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.ModifyInvalidTimeResponse")
    public com.h3c.imc.common.ws.xsd.WSCommonResult modifyInvalidTime(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        java.lang.Long param0,
        @WebParam(name = "param1", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        javax.xml.datatype.XMLGregorianCalendar param1
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "randomReqResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", partName = "parameters")
    @Action(input = "urn:randomReq", output = "urn:randomReqResponse")
    @WebMethod(action = "urn:randomReq")
    public RandomReqResponse randomReq();

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:forceLogout", output = "urn:forceLogoutResponse")
    @RequestWrapper(localName = "forceLogout", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.ForceLogout")
    @WebMethod(action = "urn:forceLogout")
    @ResponseWrapper(localName = "forceLogoutResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.ForceLogoutResponse")
    public com.h3c.imc.common.ws.xsd.WSCommonResult forceLogout(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        java.lang.String param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:applyService", output = "urn:applyServiceResponse")
    @RequestWrapper(localName = "applyService", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.ApplyService")
    @WebMethod(action = "urn:applyService")
    @ResponseWrapper(localName = "applyServiceResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.ApplyServiceResponse")
    public com.h3c.imc.common.ws.xsd.WSCommonResult applyService(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        com.h3c.imc.acmws.user.service.xsd.ApplyServiceParam param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:forceDelete", output = "urn:forceDeleteResponse")
    @RequestWrapper(localName = "forceDelete", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.ForceDelete")
    @WebMethod(action = "urn:forceDelete")
    @ResponseWrapper(localName = "forceDeleteResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.ForceDeleteResponse")
    public com.h3c.imc.common.ws.xsd.WSCommonResult forceDelete(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        java.lang.String param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:querySyncPolicyUserInfoList", output = "urn:querySyncPolicyUserInfoListResponse")
    @RequestWrapper(localName = "querySyncPolicyUserInfoList", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.QuerySyncPolicyUserInfoList")
    @WebMethod(action = "urn:querySyncPolicyUserInfoList")
    @ResponseWrapper(localName = "querySyncPolicyUserInfoListResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.QuerySyncPolicyUserInfoListResponse")
    public com.h3c.imc.acmws.user.ldap.xsd.RetAcmSyncPolicyUserInfoList querySyncPolicyUserInfoList(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        com.h3c.imc.acmws.user.ldap.xsd.AcmSyncPolicyUserQueryParam param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:removeBlackList", output = "urn:removeBlackListResponse")
    @RequestWrapper(localName = "removeBlackList", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.RemoveBlackList")
    @WebMethod(action = "urn:removeBlackList")
    @ResponseWrapper(localName = "removeBlackListResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.RemoveBlackListResponse")
    public com.h3c.imc.common.ws.xsd.WSCommonResult removeBlackList(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        java.lang.String param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:cancelAcctUser", output = "urn:cancelAcctUserResponse")
    @RequestWrapper(localName = "cancelAcctUser", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.CancelAcctUser")
    @WebMethod(action = "urn:cancelAcctUser")
    @ResponseWrapper(localName = "cancelAcctUserResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.CancelAcctUserResponse")
    public com.h3c.imc.acmws.user.accessuser.xsd.RetCancelUserInfo cancelAcctUser(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        com.h3c.imc.acmws.user.accessuser.xsd.CancelAcmUserParam param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:queryAcmUserFullInfo", output = "urn:queryAcmUserFullInfoResponse")
    @RequestWrapper(localName = "queryAcmUserFullInfo", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.QueryAcmUserFullInfo")
    @WebMethod(action = "urn:queryAcmUserFullInfo")
    @ResponseWrapper(localName = "queryAcmUserFullInfoResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.QueryAcmUserFullInfoResponse")
    public com.h3c.imc.acmws.user.accessuser.xsd.RetAcmUserFullInfo queryAcmUserFullInfo(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        java.lang.String param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:queryAcmOnlineUserList", output = "urn:queryAcmOnlineUserListResponse")
    @RequestWrapper(localName = "queryAcmOnlineUserList", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.QueryAcmOnlineUserList")
    @WebMethod(action = "urn:queryAcmOnlineUserList")
    @ResponseWrapper(localName = "queryAcmOnlineUserListResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.QueryAcmOnlineUserListResponse")
    public com.h3c.imc.acmws.user.onlineuser.xsd.RetAcmOnlineUserList queryAcmOnlineUserList(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        com.h3c.imc.acmws.user.onlineuser.xsd.AcmOnlineUserQueryParam param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:queryAcmUserByPlatUserId", output = "urn:queryAcmUserByPlatUserIdResponse")
    @RequestWrapper(localName = "queryAcmUserByPlatUserId", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.QueryAcmUserByPlatUserId")
    @WebMethod(action = "urn:queryAcmUserByPlatUserId")
    @ResponseWrapper(localName = "queryAcmUserByPlatUserIdResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.QueryAcmUserByPlatUserIdResponse")
    public com.h3c.imc.acmws.user.accessuser.xsd.RetAcmUser queryAcmUserByPlatUserId(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        java.lang.Long param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:modifyAcmUser", output = "urn:modifyAcmUserResponse")
    @RequestWrapper(localName = "modifyAcmUser", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.ModifyAcmUser")
    @WebMethod(action = "urn:modifyAcmUser")
    @ResponseWrapper(localName = "modifyAcmUserResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.ModifyAcmUserResponse")
    public com.h3c.imc.common.ws.xsd.WSCommonResult modifyAcmUser(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        com.h3c.imc.acmws.user.accessuser.xsd.ModifyAcmUserParam param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:queryAcmUserPassword", output = "urn:queryAcmUserPasswordResponse")
    @RequestWrapper(localName = "queryAcmUserPassword", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.QueryAcmUserPassword")
    @WebMethod(action = "urn:queryAcmUserPassword")
    @ResponseWrapper(localName = "queryAcmUserPasswordResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.QueryAcmUserPasswordResponse")
    public com.h3c.imc.acmws.user.accessuser.xsd.RetPassword queryAcmUserPassword(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        java.lang.String param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:sendMessage", output = "urn:sendMessageResponse")
    @RequestWrapper(localName = "sendMessage", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.SendMessage")
    @WebMethod(action = "urn:sendMessage")
    @ResponseWrapper(localName = "sendMessageResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.SendMessageResponse")
    public com.h3c.imc.common.ws.xsd.WSCommonResult sendMessage(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        java.lang.Long param0,
        @WebParam(name = "param1", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        java.lang.String param1
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:addBlackList", output = "urn:addBlackListResponse")
    @RequestWrapper(localName = "addBlackList", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.AddBlackList")
    @WebMethod(action = "urn:addBlackList")
    @ResponseWrapper(localName = "addBlackListResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.AddBlackListResponse")
    public com.h3c.imc.common.ws.xsd.WSCommonResult addBlackList(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        java.lang.String param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:queryServiceTemplateList", output = "urn:queryServiceTemplateListResponse")
    @RequestWrapper(localName = "queryServiceTemplateList", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.QueryServiceTemplateList")
    @WebMethod(action = "urn:queryServiceTemplateList")
    @ResponseWrapper(localName = "queryServiceTemplateListResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.QueryServiceTemplateListResponse")
    public com.h3c.imc.acmws.user.service.xsd.RetAcmServiceTemplateInfoList queryServiceTemplateList(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        com.h3c.imc.acmws.user.service.xsd.AcmServiceTemplateQueryParam param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:cancelBindingUser", output = "urn:cancelBindingUserResponse")
    @RequestWrapper(localName = "cancelBindingUser", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.CancelBindingUser")
    @WebMethod(action = "urn:cancelBindingUser")
    @ResponseWrapper(localName = "cancelBindingUserResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.CancelBindingUserResponse")
    public com.h3c.imc.common.ws.xsd.WSCommonResult cancelBindingUser(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        java.lang.Long param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:queryAcmUserList", output = "urn:queryAcmUserListResponse")
    @RequestWrapper(localName = "queryAcmUserList", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.QueryAcmUserList")
    @WebMethod(action = "urn:queryAcmUserList")
    @ResponseWrapper(localName = "queryAcmUserListResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.QueryAcmUserListResponse")
    public com.h3c.imc.acmws.user.accessuser.xsd.RetAcmUserList queryAcmUserList(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        com.h3c.imc.acmws.user.accessuser.xsd.AcmUserListQueryParam param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:modifyUserPassword", output = "urn:modifyUserPasswordResponse")
    @RequestWrapper(localName = "modifyUserPassword", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.ModifyUserPassword")
    @WebMethod(action = "urn:modifyUserPassword")
    @ResponseWrapper(localName = "modifyUserPasswordResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.ModifyUserPasswordResponse")
    public com.h3c.imc.common.ws.xsd.WSCommonResult modifyUserPassword(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        com.h3c.imc.acmws.user.accessuser.xsd.ModifyUserPsdParam param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:queryAcmAccessDetailList", output = "urn:queryAcmAccessDetailListResponse")
    @RequestWrapper(localName = "queryAcmAccessDetailList", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.QueryAcmAccessDetailList")
    @WebMethod(action = "urn:queryAcmAccessDetailList")
    @ResponseWrapper(localName = "queryAcmAccessDetailListResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.QueryAcmAccessDetailListResponse")
    public com.h3c.imc.acmws.user.onlineuser.xsd.RetAcmAccessDetailList queryAcmAccessDetailList(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        com.h3c.imc.acmws.user.onlineuser.xsd.AcmAccessDetailQueryParam param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
    @Action(input = "urn:queryBlackList", output = "urn:queryBlackListResponse")
    @RequestWrapper(localName = "queryBlackList", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.QueryBlackList")
    @WebMethod(action = "urn:queryBlackList")
    @ResponseWrapper(localName = "queryBlackListResponse", targetNamespace = "http://acm.imc.h3c.com/acmUserService", className = "com.h3c.imc.acm.acmuserservice.QueryBlackListResponse")
    public com.h3c.imc.acmws.user.blacklist.xsd.RetAcmBlackInfoList queryBlackList(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/acmUserService")
        com.h3c.imc.acmws.user.blacklist.xsd.AcmBlackQueryParam param0
    );
}
