package com.h3c.imc.acm.feeservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-07-27T20:12:27.713+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://acm.imc.h3c.com/feeService", name = "feeServicePortType")
@XmlSeeAlso({com.h3c.imc.common.ws.xsd.ObjectFactory.class, ObjectFactory.class, com.h3c.imc.acmws.fee.xsd.ObjectFactory.class, com.h3c.imc.acmws.fee.bill.xsd.ObjectFactory.class, com.h3c.imc.acmws.fee.accessuser.xsd.ObjectFactory.class, com.h3c.imc.acmws.fee.paymentrecord.xsd.ObjectFactory.class})
public interface FeeServicePortType {

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/feeService")
    @Action(input = "urn:cancelSuspendUserById", output = "urn:cancelSuspendUserByIdResponse")
    @RequestWrapper(localName = "cancelSuspendUserById", targetNamespace = "http://acm.imc.h3c.com/feeService", className = "com.h3c.imc.acm.feeservice.CancelSuspendUserById")
    @WebMethod(action = "urn:cancelSuspendUserById")
    @ResponseWrapper(localName = "cancelSuspendUserByIdResponse", targetNamespace = "http://acm.imc.h3c.com/feeService", className = "com.h3c.imc.acm.feeservice.CancelSuspendUserByIdResponse")
    public com.h3c.imc.common.ws.xsd.WSCommonResult cancelSuspendUserById(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/feeService")
        java.lang.Long param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/feeService")
    @Action(input = "urn:suspendUserById", output = "urn:suspendUserByIdResponse")
    @RequestWrapper(localName = "suspendUserById", targetNamespace = "http://acm.imc.h3c.com/feeService", className = "com.h3c.imc.acm.feeservice.SuspendUserById")
    @WebMethod(action = "urn:suspendUserById")
    @ResponseWrapper(localName = "suspendUserByIdResponse", targetNamespace = "http://acm.imc.h3c.com/feeService", className = "com.h3c.imc.acm.feeservice.SuspendUserByIdResponse")
    public com.h3c.imc.common.ws.xsd.WSCommonResult suspendUserById(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/feeService")
        java.lang.Long param0,
        @WebParam(name = "param1", targetNamespace = "http://acm.imc.h3c.com/feeService")
        javax.xml.datatype.XMLGregorianCalendar param1,
        @WebParam(name = "param2", targetNamespace = "http://acm.imc.h3c.com/feeService")
        java.lang.Integer param2
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/feeService")
    @Action(input = "urn:selfPay", output = "urn:selfPayResponse")
    @RequestWrapper(localName = "selfPay", targetNamespace = "http://acm.imc.h3c.com/feeService", className = "com.h3c.imc.acm.feeservice.SelfPay")
    @WebMethod(action = "urn:selfPay")
    @ResponseWrapper(localName = "selfPayResponse", targetNamespace = "http://acm.imc.h3c.com/feeService", className = "com.h3c.imc.acm.feeservice.SelfPayResponse")
    public com.h3c.imc.common.ws.xsd.WSCommonResult selfPay(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/feeService")
        com.h3c.imc.acmws.fee.xsd.SelfPaymentInfo param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/feeService")
    @Action(input = "urn:queryBillDetailByBillId", output = "urn:queryBillDetailByBillIdResponse")
    @RequestWrapper(localName = "queryBillDetailByBillId", targetNamespace = "http://acm.imc.h3c.com/feeService", className = "com.h3c.imc.acm.feeservice.QueryBillDetailByBillId")
    @WebMethod(action = "urn:queryBillDetailByBillId")
    @ResponseWrapper(localName = "queryBillDetailByBillIdResponse", targetNamespace = "http://acm.imc.h3c.com/feeService", className = "com.h3c.imc.acm.feeservice.QueryBillDetailByBillIdResponse")
    public com.h3c.imc.acmws.fee.bill.xsd.RetAcmBillDetailList queryBillDetailByBillId(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/feeService")
        java.lang.Long param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/feeService")
    @Action(input = "urn:queryBillByUserId", output = "urn:queryBillByUserIdResponse")
    @RequestWrapper(localName = "queryBillByUserId", targetNamespace = "http://acm.imc.h3c.com/feeService", className = "com.h3c.imc.acm.feeservice.QueryBillByUserId")
    @WebMethod(action = "urn:queryBillByUserId")
    @ResponseWrapper(localName = "queryBillByUserIdResponse", targetNamespace = "http://acm.imc.h3c.com/feeService", className = "com.h3c.imc.acm.feeservice.QueryBillByUserIdResponse")
    public com.h3c.imc.acmws.fee.bill.xsd.RetAcmUserBillList queryBillByUserId(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/feeService")
        java.lang.Long param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/feeService")
    @Action(input = "urn:queryAcmUserService", output = "urn:queryAcmUserServiceResponse")
    @RequestWrapper(localName = "queryAcmUserService", targetNamespace = "http://acm.imc.h3c.com/feeService", className = "com.h3c.imc.acm.feeservice.QueryAcmUserService")
    @WebMethod(action = "urn:queryAcmUserService")
    @ResponseWrapper(localName = "queryAcmUserServiceResponse", targetNamespace = "http://acm.imc.h3c.com/feeService", className = "com.h3c.imc.acm.feeservice.QueryAcmUserServiceResponse")
    public com.h3c.imc.acmws.fee.accessuser.xsd.RetAcmUserServiceList queryAcmUserService(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/feeService")
        java.lang.String param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/feeService")
    @Action(input = "urn:queryBalance", output = "urn:queryBalanceResponse")
    @RequestWrapper(localName = "queryBalance", targetNamespace = "http://acm.imc.h3c.com/feeService", className = "com.h3c.imc.acm.feeservice.QueryBalance")
    @WebMethod(action = "urn:queryBalance")
    @ResponseWrapper(localName = "queryBalanceResponse", targetNamespace = "http://acm.imc.h3c.com/feeService", className = "com.h3c.imc.acm.feeservice.QueryBalanceResponse")
    public com.h3c.imc.acmws.fee.xsd.RetUserBalance queryBalance(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/feeService")
        java.lang.String param0
    );

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/feeService")
    @Action(input = "urn:pay", output = "urn:payResponse")
    @RequestWrapper(localName = "pay", targetNamespace = "http://acm.imc.h3c.com/feeService", className = "com.h3c.imc.acm.feeservice.Pay")
    @WebMethod(action = "urn:pay")
    @ResponseWrapper(localName = "payResponse", targetNamespace = "http://acm.imc.h3c.com/feeService", className = "com.h3c.imc.acm.feeservice.PayResponse")
    public com.h3c.imc.common.ws.xsd.WSCommonResult pay(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/feeService")
        com.h3c.imc.acmws.fee.xsd.PaymentInfo param0
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "randomReqResponse", targetNamespace = "http://acm.imc.h3c.com/feeService", partName = "parameters")
    @Action(input = "urn:randomReq", output = "urn:randomReqResponse")
    @WebMethod(action = "urn:randomReq")
    public RandomReqResponse randomReq();

    @WebResult(name = "return", targetNamespace = "http://acm.imc.h3c.com/feeService")
    @Action(input = "urn:queryPaymentRecord", output = "urn:queryPaymentRecordResponse")
    @RequestWrapper(localName = "queryPaymentRecord", targetNamespace = "http://acm.imc.h3c.com/feeService", className = "com.h3c.imc.acm.feeservice.QueryPaymentRecord")
    @WebMethod(action = "urn:queryPaymentRecord")
    @ResponseWrapper(localName = "queryPaymentRecordResponse", targetNamespace = "http://acm.imc.h3c.com/feeService", className = "com.h3c.imc.acm.feeservice.QueryPaymentRecordResponse")
    public com.h3c.imc.acmws.fee.paymentrecord.xsd.RetPaymentRecordList queryPaymentRecord(
        @WebParam(name = "param0", targetNamespace = "http://acm.imc.h3c.com/feeService")
        java.lang.Long param0
    );
}
