package com.h3c.imc.imcplatservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-07-27T17:59:59.513+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://imc.h3c.com/imcplatService", name = "imcplatServicePortType")
@XmlSeeAlso({ObjectFactory.class, com.h3c.imc.common.ws.xsd.ObjectFactory.class})
public interface ImcplatServicePortType {

    @WebResult(name = "return", targetNamespace = "http://imc.h3c.com/imcplatService")
    @Action(input = "urn:login", output = "urn:loginResponse")
    @RequestWrapper(localName = "login", targetNamespace = "http://imc.h3c.com/imcplatService", className = "com.h3c.imc.imcplatservice.Login")
    @WebMethod(action = "urn:login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://imc.h3c.com/imcplatService", className = "com.h3c.imc.imcplatservice.LoginResponse")
    public com.h3c.imc.common.ws.xsd.WSCommonResult login(
        @WebParam(name = "param0", targetNamespace = "http://imc.h3c.com/imcplatService")
        java.lang.String param0,
        @WebParam(name = "param1", targetNamespace = "http://imc.h3c.com/imcplatService")
        java.lang.String param1
    );

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "logoutResponse", targetNamespace = "http://imc.h3c.com/imcplatService", partName = "parameters")
    @Action(input = "urn:logout", output = "urn:logoutResponse")
    @WebMethod(action = "urn:logout")
    public LogoutResponse logout();
}
